"""game

Revision ID: 54fd328f2687
Revises: ec1a1cc7e4f8
Create Date: 2021-01-06 14:59:59.734294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54fd328f2687'
down_revision = 'ec1a1cc7e4f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('date', sa.Text(), nullable=True),
    sa.Column('disc', sa.Text(), nullable=True),
    sa.Column('d_url', sa.Text(), nullable=True),
    sa.Column('i_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    # ### end Alembic commands ###
