"""game

Revision ID: b773335779b8
Revises: aa7f449daa8f
Create Date: 2021-01-06 21:57:32.352584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b773335779b8'
down_revision = 'aa7f449daa8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('size', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'size')
    # ### end Alembic commands ###
